### PR TITLE
New Develop Version

### PR DESCRIPTION
**Pull request by nickbe**
#43 is now additionally solved

### CODE REVIEW

**Comment by nickbe** [comment]
I must admit I have no idea which conflicts there are and how to resolve them.
As far as I'm aware all updates should be newer than your last develop version.

**Comment by satrun77** [comment]
Most likely the conflict in the the compiled css and js files. You have layout changes in this pull request!

**Comment by nickbe** [comment]
Yes, I changed the login screen and I changed the history view

**Comment by nickbe** [comment]
Since I have no clue (and I tried to follow github instructions) how to solve the conflict, can you merge anyway and just ignore the compiled stuff?

How can I avoid this from now on?

**Comment by satrun77** [comment]
Some of the changes in this pull request were merged.
Changes not merged:
- Login page style changes.
- User restricted status.
- gitignore & composer changes.

**Comment by nickbe** [comment]
Did you leave out the status 'restricted' or the complete option to deactivate a user?

**Comment by satrun77** [comment]
Just removed the constants 'restricted' because it is not used.

**Comment by nickbe** [comment]
Ah ok. 

What about the login background image? I thought when we give the visuals a little overhaul - we might also give the admin an option to upload his own login background image, his own little logo and let him select his favorite color which we use for certain highlighting purposes later. That a good idea?

**Comment by satrun77** [comment]
It is nice to have personalised application. I think it should be seperate task to complete.

**Comment by nickbe** [comment]
Agreed

**Pull request closed without merging**
