### PR TITLE
Tag handling and visibilty improvement

### PR DESCRIPTION
**Pull request by nickbe**
Each tag does now have a role selector. Depending on the users role he
can either set/view certain tags or not. Also the kanban view reacts
properly according to the same tag settings.

### CODE REVIEW

**Comment by nickbe** [comment]
I only corrected the requirements for PSR-2.
So unix linefeeds at the end of line, spaces for tags and so on,
Don't ask my what the conflicts are - since you didn't make any commits in the meanwhile as far as I can see.

But the changes should be easy enough to merge anyway.

**Comment by nickbe** [comment]
Github Desktop tends to ignore my ignores :)
So maybe the problem lies with the files .gitignore and composer.lock. 
No matter how often I mark them to ignore.... he pushes them anyway.

**Comment by satrun77** [comment]
Don't worry about merge conflict. I merge the changes per commit and fix anything that is conflicting.

With git you can add global ignore file: https://help.github.com/articles/ignoring-files.

Most likely the conflict is with the css files. CSS file should not be commit to repository. I only added them here so people don't have to install the CSS preprocessor and execute gulp. I normally commit the CSS and JS build in a seperate commit, so its not part of the change.

**Comment by nickbe** [comment]
Ah ok. Thanks :)
Hope you like what I did. It's in production now since yesterday and my team loves the new features. Even if it's basically only a small change :)

**Comment by satrun77** [comment]
Your pull request includes other changes related to hiding the open and close tags from the issue. I have a test project with 3 issues and status open, testing, tag1 (accessible for managers only), close

- Kanban view shows one column for developers testing.
- Kanban view shows 2 columns for managers [testing, tag1].

Issues:
1) issue 1 is closed ==> shows in the kanban under testing all users.
2) issue 2 opened   ==> does not show at all to all users in kanban view.
3) issue 3 opened with status tag1 ==> shows to managers in the kanban view.

I understand the limit tag and like the idea, just want to understand the entire flow of it. The other changes in this pull request just complicate things and confuse me! :)

Can you please make the pull request relate to one change only.

**Comment by nickbe** [comment]
I'll explain this tomorrow and make corrections after the weekend when I'm back home :) ok?

**Comment by nickbe** [comment]
I definetely seem to have overlooked some small problems. And while writing down a description of what I want to achieve in detail and some case examples - I found some loose ends too which I have to see through first.

Can you tell me what happens right now when you actually close an issue?

**Comment by satrun77** [comment]
- I understand the feature to limit tags by role. This is good idea.
- I still don't understand why remove the open and close tags from kanban view and change issue form to dropdown list with open and archive. To me this is another change seperate from this pull request. Also, there is no details on the request about these changes.

**Comment by nickbe** [comment]
Beside the fact that I think all the tags should be completely renamable, I also think the old [ open ]  tag is completely obsolete and also wrong because for once every ticket which is not closed is automatically open. Open tickets should be listed under "Open Tickets", but without the old **OPEN** status.

**IF** I want to have an [ open ] tag I'd like to be able to define it myself but in a different sense and also rename like any other.

Let's assume we have the following tags:

Type:   [ BUG ]  [ CRITICAL ]  [ IDEA ]  [ FEATURE ]  [ CHANGE ]  [ QUESTION ]
Resolve:    [ FIXED ]  [  REJECTED ]  [ ANSWERED ]
Also from our status tag list we selected these statuses:
[ DRAFT ]  [ NEW ]  [ BACKLOG ]  [ DISCUSS ]  [ OPEN ]  [ WORKING ]  [  REVIEW ]  [  RELEASE ] 

Now a user creates a new ticket - the first status in order is [ NEW ], so it's set as default.
[ NEW ] was not selected for kanban, but maybe the others. Type of the ticket is [ BUG ]

Being a manager I set the ticket to [ DISCUSS ]. Role limit of [ DISCUSS ] is "Manager", so users and developers will not see the column [ DISCUSS ] at all in the kanban view.

Users/developers can however open the ticket quite normally under projects/tickets - however since the status is set to a value they don't have access to, ticket edit mode will only show this specific status - which simply results in the effect that they cannot change it.

After I decide that the bug is a real stopper, I set the type to [ CRITICAL ] and the status to [ OPEN ]. now the developers can see the ticket in the kanban - knowing it's his turn now to fix the bug. He sets the status to [ WORKING ] and starts fixing. After he's finished he sets the status to [ REVIEW ] 

I also think that users should only see kanban views depending of a configuration option "Users can see kanban (read only)". Personally I wouldn't want them to see them at all. 

Now the user checks the ticket list and finds the **Resolve** tag set to [ FIXED ] and the status has just moved to [ RELEASE ]. Almost there...

Last thing is to close the ticket. If the user is also the creator then he can close the ticket. Or the ticket is closed by me as a manager. So if the ticket is closed it should mean settings a distinct database flag to true. The ticket moves from the **open** to the **closed** list. Now a virtual [ CLOSED ] tag should be displayed - but not as a real tag.

For me a closed column in the kanban view would mean up to 63 tickets in one column. Therefore I don't think it makes sense. 

Finally the dropdown for a tag's role limit should have the entries "None (creator only)", "Manager", "Developer", "User". 

Here Administrators should be treated as managers. And **None** would be required for example for the [ DRAFT ] status - Meaning that only the creator of an issue can see it at all.

I hope this explains my thoughts.

**Comment by satrun77** [comment]
Ok. I see your point. The tag implementation is simple but does not work that well.

- The role_limit not going to work by role id, if you want a tag to be limited to specific user.
- There is column "status" in issue table. This is the original status flag (yes or not values) to indicate if the issue open or close. This flag still used. I think with your changes we need to use this instead of open and close tag. based on this flag the label is going to be rendered with fixed colors.
- The kanban view must be changed to queries all of the issues that are not set to status =0. This is to exclude the closed issues.
- Readonly kanban should be left out of this pull request for now.

**Comment by satrun77** [comment]
I merged your code to develop branch and made few code style changes. 

I don't see this complete yet. There are more work to be done here to cover all of the requirements above.

**Comment by nickbe** [comment]
Cool. Let me check this out tonight.
And you're right of course. This isn't complete yet.

**Comment by nickbe** [comment]
Hi Mohammed,

I just saw your latest commit and I've tried to find out what's working now.
Can you give me a quick update what you did so far?

Cheers
Nick
Am Mo., Mai 2, 2016 12:01 schrieb Mohamed Alsharaf : I merged your code to develop branch and made few code style changes. 
 I don't see this complete yet. There are more work to be done here to cover all of the requirements above.

**Comment by satrun77** [comment]
The commits I have being pushing are different changes without testing yet. Basically it should work in the same functionality you proposed above.
- Tags can be limited by roles.
- Removed open and closed tag. established the original issue status flag.
- Virtual (open/closed) label will show in the issue page depending on its status.
- Open issues tab does not shows the open label tag. I think this is redundant.
- Kanban shows only status tags without open or closed.
- The migration script will delete everything related to the tags open and closed.

Not complete yet:
- Option to delete a tag.
- Testing...
- Update test scripts.

**Comment by nickbe** [comment]
A virtual closed tag is good, but I'd like to use **open** as an indicator for tickets that are "open" to be worked on. in other words: open should not be a "special" status anymore.

Otherwise a status flow like the following wouldn't work:

STATUS:     New      Backlog      Open          Working       Ready          Release
LIMROLE:   User     Manager    Developer   Developer    Developer   Manager

- Users can only set "New/Unconfirmed" and thus are not able to change it. I don't think they should see kanban at all.

- Developers can set tickets between "Open", "Working" and  "Ready". They can also see these 3 columns in kanban.

- Managers/Admins can set and see all tags/columns.

1. Since New/Unconfirmed is first in line, all new issues get the status "New/Unconfirmed"

2. A manager can decide to set the status of an issue to "Backlog" and the ticket is not visible to users and developers anymore. Since I would revoke access to "BackLog" from Developers/Users they can still see the issue in the ticket list, but should only see one status in the issue - not being able to change it. And they would not see this column in the kanban at all.

3. If a manager decides to set the status to "Release" then the issue also vanishes from the kanban view for users/developers. Still It's visible in the ticket list, but again they can only see one status "Release" in the ticket. They cannot change the state.

4. If I close a ticket then it should show up in the "closed tickets" list.

**Comment by satrun77** [comment]
You can still do that now.

You are free to create any status tag you would like including open and closed. Tags are just a label attached to an issue and visible in kanban view.

There is a flag with each issue that is set to 1 for open/new/unconfirmed and 0 closed. This flag can be change in language file to anything you want. It only to indicate if an issue is active or not.

**Comment by nickbe** [comment]
So you mean I can just delete the old "open"/"closed" tags now?

**Comment by satrun77** [comment]
the latest commit include migration script that will delete these tags.

Tonight or tomorrow I will implement the option to delete any tag.

**Comment by nickbe** [comment]
Got it. As always - thanks for your work.

**Comment by satrun77** [comment]
I think I have implemented everything here. Try it and let me know.

**Comment by nickbe** [comment]
Awesome :)  I'm upgrading my live system later today and then play through all the various scenarios over the weekend.

- The only thing so far is the fact is the kanban view.

>As a manager it would be great to be able to switch between all projects/ issues (manager view - as it does now) and my issue (developer view - as it does when I log in as a developer).

one way way might be to have and additional pair of toggle buttons beside the two green buttons under **My Issues**.  [ Manager View | Developer View | User View ]

- Manager View: Show all issues (exactly like it does now=
- Developer View: Show issues the same way as it does for a developer
- User View: Only show tickets I've created myself.

And as always.
Thanks!

**Comment by nickbe** [comment]
Further enhancements should be discussed elsewhere.
Thanks and closed.

**Pull request closed without merging**
